### ISSUE TITLE
Default host should be 0.0.0.0 not localhost

### ISSUE THREAD

**Issue by inadarei** [randallsquared/waitstaff#1]
From documentation: "If the hostname is missing, it will default to localhost"

I think it makes more sense to default to 0.0.0.0 instead of localhost

**Comment by randallsquared** [comment]
For servers, 0.0.0.0 means every available address.   I wasn't sure what that would mean for a client, but some research seems to indicate that it's a synonym for localhost.   Can you say more about why it would be better to use '0.0.0.0'?

**Comment by inadarei** [comment]
I am pretty sure 0.0.0.0 means the same thing for clients that it means for servers - all local addresses, whereas `localhost` may be only one of those.

**Comment by randallsquared** [comment]
That would mean a single `connect(3306, '0.0.0.0')` call would try to open as many different connections as the host has interfaces?  There's basically no provision for that in the node net API, and a fix landed last year to ensure that `libuv`, node's networking lib, treats attempts to connect to '0.0.0.0' as localhost connections on Windows the same as it does on Linux.

That said, I don't think changing it would hurt any functionality, but given that for clients it means "localhost", I think it might be confusing to people who expect localhost to only live at 127.0.0.0/8 .

References:
- https://github.com/libuv/libuv/commit/2b32e77bb6f41e2786168ec0f32d1f0fcc78071b
- https://github.com/nodejs/node/issues/14900

**Comment by inadarei** [comment]
What you are saying makes sense. Closing the issue.
